// const restaurentList = [
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "279741",
//         name: "Easy Bites by Hotel Empire",
//         uuid: "d9ab4a4f-8464-4352-a387-9cd2b07842cc",
//         city: "1",
//         area: "Marathahalli",
//         totalRatingsString: "1000+ ratings",
//         cloudinaryImageId: "d06b7fa84cb8f8193f60d4c2de172347",
//         cuisines: ["Snacks", "Fast Food", "Beverages"],
//         tags: [],
//         costForTwo: 20000,
//         costForTwoString: "₹200 FOR TWO",
//         deliveryTime: 44,
//         minDeliveryTime: 44,
//         maxDeliveryTime: 44,
//         slaString: "44 MINS",
//         lastMileTravel: 3.5,
//         slugs: {
//           restaurent: "easy-bites-marathahalli-marathahalli",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "SITE NO.4,SY NO.7/3,VARTHUR HOBLI,BANGALORE-560037,District-B.B.M.P East,STATE-Karnataka",
//         locality: "BEML Layout",
//         parentId: 8503,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         ribbon: [
//           {
//             type: "PROMOTED",
//           },
//         ],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 3800,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 3800,
//           message: "",
//           title: "Delivery Charge",
//           amount: "3800",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "cid=7137326~p=1~eid=00000188-cd90-b604-1228-3c3900af0103",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "3.5 kms",
//         hasSurge: false,
//         aggregatedDiscountInfoV3: {
//           header: "10% OFF",
//           subHeader: "UPTO ₹40",
//           discountTag: "",
//           headerTypeV2: 0,
//         },
//         sla: {
//           restaurentId: "279741",
//           deliveryTime: 44,
//           minDeliveryTime: 44,
//           maxDeliveryTime: 44,
//           lastMileTravel: 3.5,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: true,
//         avgRating: "4.0",
//         totalRatings: 1000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "221738",
//         name: "Meghana Foods",
//         uuid: "106f4556-6804-4554-8c68-ee875d6acf65",
//         city: "1",
//         area: "Brookefield",
//         totalRatingsString: "10000+ ratings",
//         cloudinaryImageId: "aqsnrylokzpn45qhg1pb",
//         cuisines: [
//           "Biryani",
//           "Andhra",
//           "South Indian",
//           "North Indian",
//           "Chinese",
//           "Seafood",
//         ],
//         tags: [],
//         costForTwo: 50000,
//         costForTwoString: "₹500 FOR TWO",
//         deliveryTime: 53,
//         minDeliveryTime: 53,
//         maxDeliveryTime: 53,
//         slaString: "53 MINS",
//         lastMileTravel: 2.4000000953674316,
//         slugs: {
//           restaurent: "meghana-foods-mahadevpura-mahadevpura",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address: "Raj Pinnacle, Mahadevapura, Bengaluru, Karnataka, India",
//         locality: "Mahadevpura",
//         parentId: 635,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 2800,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 2800,
//           message: "",
//           title: "Delivery Charge",
//           amount: "2800",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "2.4 kms",
//         hasSurge: false,
//         sla: {
//           restaurentId: "221738",
//           deliveryTime: 53,
//           minDeliveryTime: 53,
//           maxDeliveryTime: 53,
//           lastMileTravel: 2.4000000953674316,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.3",
//         totalRatings: 10000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "280569",
//         name: "Empire Juices and Desserts",
//         uuid: "86951528-7018-457a-a488-8f64577d114c",
//         city: "1",
//         area: "Marathahalli",
//         totalRatingsString: "500+ ratings",
//         cloudinaryImageId: "vh4dlykbvombevwyplyl",
//         cuisines: ["Juices", "Ice Cream"],
//         tags: [],
//         costForTwo: 20000,
//         costForTwoString: "₹200 FOR TWO",
//         deliveryTime: 47,
//         minDeliveryTime: 47,
//         maxDeliveryTime: 47,
//         slaString: "47 MINS",
//         lastMileTravel: 3.5,
//         slugs: {
//           restaurent: "the-empire-juice-shop-marathahalli-marathahalli",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address: "SITE NO.4, SY NO.7/3, VARTHUR HOBLI, BANGALORE-560037",
//         locality: "BEML Layout",
//         parentId: 387289,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         ribbon: [
//           {
//             type: "PROMOTED",
//           },
//         ],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 3800,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 3800,
//           message: "",
//           title: "Delivery Charge",
//           amount: "3800",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "cid=7137347~p=22~eid=00000188-cd90-b604-1228-3c4000af1679",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "3.5 kms",
//         hasSurge: false,
//         aggregatedDiscountInfoV3: {
//           header: "20% OFF",
//           subHeader: "UPTO ₹50",
//           discountTag: "",
//           headerTypeV2: 0,
//         },
//         sla: {
//           restaurentId: "280569",
//           deliveryTime: 47,
//           minDeliveryTime: 47,
//           maxDeliveryTime: 47,
//           lastMileTravel: 3.5,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: true,
//         avgRating: "4.2",
//         totalRatings: 500,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "690129",
//         name: "Kritunga restaurent",
//         uuid: "5bc1017a-12af-44d0-946f-3a0d9a6d6137",
//         city: "1",
//         area: "Whitefield",
//         totalRatingsString: "500+ ratings",
//         cloudinaryImageId: "a58675e8e5968e4ec50cfbfdc6648728",
//         cuisines: ["North Indian", "Indian"],
//         tags: [],
//         costForTwo: 60000,
//         costForTwoString: "₹600 FOR TWO",
//         deliveryTime: 28,
//         minDeliveryTime: 28,
//         maxDeliveryTime: 28,
//         slaString: "28 MINS",
//         lastMileTravel: 4,
//         slugs: {
//           restaurent: "kritunga-restaurent-whitefield-whitefield-2",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "5, Whitefield, Vijayanagar, EPIP Zone, Bengaluru, Karnataka 560066, India",
//         locality: "Vijayanagar",
//         parentId: 20088,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 3800,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 3800,
//           message: "",
//           title: "Delivery Charge",
//           amount: "3800",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "4 kms",
//         hasSurge: false,
//         sla: {
//           restaurentId: "690129",
//           deliveryTime: 28,
//           minDeliveryTime: 28,
//           maxDeliveryTime: 28,
//           lastMileTravel: 4,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.0",
//         totalRatings: 500,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "420659",
//         name: "Sri Lakshmi Biryani",
//         uuid: "eb227257-1596-441a-9c84-8265417d2d19",
//         city: "1",
//         area: "Marathahalli",
//         totalRatingsString: "5000+ ratings",
//         cloudinaryImageId: "n7pn6ilfponvcatp0n73",
//         cuisines: ["Biryani", "North Indian", "Snacks"],
//         tags: [],
//         costForTwo: 20000,
//         costForTwoString: "₹200 FOR TWO",
//         deliveryTime: 47,
//         minDeliveryTime: 47,
//         maxDeliveryTime: 47,
//         slaString: "47 MINS",
//         lastMileTravel: 5,
//         slugs: {
//           restaurent: "sri-lakshmi-biryani-kadubeesanahalli-kadubeesanahalli",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "No 15&16 Srinivasa Reddy building, Lakshmi Narayana temple road, manunatha layout, munnekoll Bangalore 560037",
//         locality: "Manunatha Layout",
//         parentId: 193940,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 5300,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 5300,
//           message: "",
//           title: "Delivery Charge",
//           amount: "5300",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "5 kms",
//         hasSurge: false,
//         aggregatedDiscountInfoV3: {
//           header: "₹125 OFF",
//           subHeader: "ABOVE ₹599",
//           discountTag: "FLAT DEAL",
//           headerTypeV2: 0,
//         },
//         sla: {
//           restaurentId: "420659",
//           deliveryTime: 47,
//           minDeliveryTime: 47,
//           maxDeliveryTime: 47,
//           lastMileTravel: 5,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.6",
//         totalRatings: 5000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "113231",
//         name: "NISO Chinese restaurent",
//         uuid: "8a53ddec-e0cc-417b-adad-dd81d9bacb65",
//         city: "1",
//         area: "KR Puram",
//         totalRatingsString: "5000+ ratings",
//         cloudinaryImageId: "xyec2vrovt0tt7ncbgr8",
//         cuisines: ["Chinese", "Thai", "Seafood"],
//         tags: [],
//         costForTwo: 30000,
//         costForTwoString: "₹300 FOR TWO",
//         deliveryTime: 38,
//         minDeliveryTime: 38,
//         maxDeliveryTime: 38,
//         slaString: "38 MINS",
//         lastMileTravel: 3.5,
//         slugs: {
//           restaurent: "niso-chinese-restaurent-test-prod-area",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "#15, 1st floor, Kodigehalli Main road, Ayyappa Nagar, KR Puram, Bangalore 560036",
//         locality: "Ayyappa Nagar",
//         parentId: 21384,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         ribbon: [
//           {
//             type: "PROMOTED",
//           },
//         ],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 3800,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 3800,
//           message: "",
//           title: "Delivery Charge",
//           amount: "3800",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "cid=7128439~p=7~eid=00000188-cd90-b604-1228-3c3b00af0758",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "3.5 kms",
//         hasSurge: false,
//         aggregatedDiscountInfoV3: {
//           header: "₹100 OFF",
//           subHeader: "ABOVE ₹299",
//           discountTag: "FLAT DEAL",
//           headerTypeV2: 0,
//         },
//         sla: {
//           restaurentId: "113231",
//           deliveryTime: 38,
//           minDeliveryTime: 38,
//           maxDeliveryTime: 38,
//           lastMileTravel: 3.5,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: true,
//         avgRating: "4.0",
//         totalRatings: 5000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "262167",
//         name: "Hotel Empire",
//         uuid: "c087d70f-5cff-49ec-8b8a-e8b1a07a1977",
//         city: "1",
//         area: "Brookefields",
//         totalRatingsString: "10000+ ratings",
//         cloudinaryImageId: "weuqdjwzk3azoijehnel",
//         cuisines: ["North Indian", "Kebabs", "Biryani"],
//         tags: [],
//         costForTwo: 40000,
//         costForTwoString: "₹400 FOR TWO",
//         deliveryTime: 47,
//         minDeliveryTime: 47,
//         maxDeliveryTime: 47,
//         slaString: "47 MINS",
//         lastMileTravel: 3.5,
//         slugs: {
//           restaurent: "hotel-empire-marathahalli-marathahalli",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "EMPIRE restaurent ASK TOWERS,NO 7/3 OF THOOBARAHALLI VILLAGE,VARTHUR VILLAGE,VARTHOOR HOBLI 560037",
//         locality: "",
//         parentId: 475,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 3800,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 3800,
//           message: "",
//           title: "Delivery Charge",
//           amount: "3800",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "3.5 kms",
//         hasSurge: false,
//         aggregatedDiscountInfoV3: {
//           header: "10% OFF",
//           subHeader: "UPTO ₹40",
//           discountTag: "",
//           headerTypeV2: 0,
//         },
//         sla: {
//           restaurentId: "262167",
//           deliveryTime: 47,
//           minDeliveryTime: 47,
//           maxDeliveryTime: 47,
//           lastMileTravel: 3.5,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.9",
//         totalRatings: 10000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "78138",
//         name: "Imperio restaurent",
//         uuid: "7251486d-55a6-4ca0-ac99-e1e6cd4a7834",
//         city: "1",
//         area: "Marathahalli",
//         totalRatingsString: "10000+ ratings",
//         cloudinaryImageId: "a1629b9c7f59577a55411e94425c6d99",
//         cuisines: [
//           "Chinese",
//           "South Indian",
//           "North Indian",
//           "Desserts",
//           "Kerala",
//           "Andhra",
//           "Beverages",
//           "Mughlai",
//           "Seafood",
//           "Punjabi",
//           "Hyderabadi",
//           "Thai",
//         ],
//         tags: [],
//         costForTwo: 30000,
//         costForTwoString: "₹300 FOR TWO",
//         deliveryTime: 58,
//         minDeliveryTime: 58,
//         maxDeliveryTime: 58,
//         slaString: "58 MINS",
//         lastMileTravel: 3,
//         slugs: {
//           restaurent: "imperio-restaurent-whitefield-whitefield-3",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "3A, squre plaza,ground floor, itpl main road,Kundalahalli,banglore.",
//         locality: "kundalahalli",
//         parentId: 5610,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 3800,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 3800,
//           message: "",
//           title: "Delivery Charge",
//           amount: "3800",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "3 kms",
//         hasSurge: false,
//         aggregatedDiscountInfoV3: {
//           header: "20% OFF",
//           subHeader: "UPTO ₹50",
//           discountTag: "",
//           headerTypeV2: 0,
//         },
//         sla: {
//           restaurentId: "78138",
//           deliveryTime: 58,
//           minDeliveryTime: 58,
//           maxDeliveryTime: 58,
//           lastMileTravel: 3,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.9",
//         totalRatings: 10000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "222837",
//         name: "Potful - Claypot Biryanis",
//         uuid: "42828768-0847-44b3-af7d-2902ddacbb5f",
//         city: "1",
//         area: "Brookefield",
//         totalRatingsString: "5000+ ratings",
//         cloudinaryImageId: "gnmsqmvqjadtsjvmp0hx",
//         cuisines: ["Biryani", "Kebabs", "North Indian", "Mughlai"],
//         tags: [],
//         costForTwo: 50000,
//         costForTwoString: "₹500 FOR TWO",
//         deliveryTime: 61,
//         minDeliveryTime: 61,
//         maxDeliveryTime: 61,
//         slaString: "61 MINS",
//         lastMileTravel: 2.5999999046325684,
//         slugs: {
//           restaurent: "potful-whitefield-whitefield",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "1st floor ,Graphite India Main Road, Phase 2, Brookefield, Bangalore",
//         locality: "Graphite India Main Road",
//         parentId: 160121,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         ribbon: [
//           {
//             type: "PROMOTED",
//           },
//         ],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 2800,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 2800,
//           message: "",
//           title: "Delivery Charge",
//           amount: "2800",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "cid=7147735~p=10~eid=00000188-cd90-b604-1228-3c3c00af0a52",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "2.5 kms",
//         hasSurge: false,
//         aggregatedDiscountInfoV3: {
//           header: "40% OFF",
//           subHeader: "UPTO ₹80",
//           discountTag: "",
//           headerTypeV2: 0,
//         },
//         sla: {
//           restaurentId: "222837",
//           deliveryTime: 61,
//           minDeliveryTime: 61,
//           maxDeliveryTime: 61,
//           lastMileTravel: 2.5999999046325684,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: true,
//         avgRating: "4.2",
//         totalRatings: 5000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "210119",
//         name: "Sri Jayadurga Biryani",
//         uuid: "13927ae4-7437-4d24-959e-888585c704e8",
//         city: "1",
//         area: "Marathahalli",
//         totalRatingsString: "10000+ ratings",
//         cloudinaryImageId: "e5k8viofbtrxxo75lxdy",
//         cuisines: ["Biryani", "South Indian", "Andhra", "Hyderabadi", "Snacks"],
//         tags: [],
//         costForTwo: 30000,
//         costForTwoString: "₹300 FOR TWO",
//         deliveryTime: 38,
//         minDeliveryTime: 38,
//         maxDeliveryTime: 38,
//         slaString: "38 MINS",
//         lastMileTravel: 5,
//         slugs: {
//           restaurent: "sri-jayadurga-biryani-marathahalli-marathahalli",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "Sri Jaya Durga restaurent, OPP AMRUTHA BAKERY, LAKSHMI NARAYANA TEMPLE ROAD, MUNNEKOLALA, MARATHAHALLI, BANGALORE",
//         locality: "Munnekollal",
//         parentId: 14529,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 5300,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 5300,
//           message: "",
//           title: "Delivery Charge",
//           amount: "5300",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "5 kms",
//         hasSurge: false,
//         aggregatedDiscountInfoV3: {
//           header: "₹125 OFF",
//           subHeader: "ABOVE ₹599",
//           discountTag: "FLAT DEAL",
//           headerTypeV2: 0,
//         },
//         sla: {
//           restaurentId: "210119",
//           deliveryTime: 38,
//           minDeliveryTime: 38,
//           maxDeliveryTime: 38,
//           lastMileTravel: 5,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.6",
//         totalRatings: 10000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "424658",
//         name: "Asha Tiffins",
//         uuid: "d79cd5d9-7158-45f1-a198-e563f0e46406",
//         city: "1",
//         area: "Aecs Layout",
//         totalRatingsString: "10000+ ratings",
//         cloudinaryImageId: "hpncnz3sfv3gigsukkts",
//         cuisines: ["South Indian"],
//         tags: [],
//         costForTwo: 20000,
//         costForTwoString: "₹200 FOR TWO",
//         deliveryTime: 39,
//         minDeliveryTime: 39,
//         maxDeliveryTime: 39,
//         slaString: "39 MINS",
//         lastMileTravel: 2.700000047683716,
//         slugs: {
//           restaurent: "asha-tiffins-marathahalli-marathahalli",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "#551,AECS Layout main road, 'B' Block AECS Layout,Opp.BBMP ward office,Marathahalli,Bangalore - 560037",
//         locality: "B Block",
//         parentId: 236243,
//         unserviceable: false,
//         veg: true,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 2800,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 2800,
//           message: "",
//           title: "Delivery Charge",
//           amount: "2800",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "2.7 kms",
//         hasSurge: false,
//         aggregatedDiscountInfoV3: {
//           header: "30% OFF",
//           subHeader: "UPTO ₹70",
//           discountTag: "",
//           headerTypeV2: 0,
//         },
//         sla: {
//           restaurentId: "424658",
//           deliveryTime: 39,
//           minDeliveryTime: 39,
//           maxDeliveryTime: 39,
//           lastMileTravel: 2.700000047683716,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.4",
//         totalRatings: 10000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "453491",
//         name: "Sharief Bhai",
//         uuid: "2acd3dc6-9889-4bc2-ba73-1cfaf6abb51c",
//         city: "1",
//         area: "Marathahalli",
//         totalRatingsString: "5000+ ratings",
//         cloudinaryImageId: "p6afpchuugk5pbmqxty8",
//         cuisines: [
//           "Mughlai",
//           "Biryani",
//           "Arabian",
//           "Kebabs",
//           "Beverages",
//           "Desserts",
//         ],
//         tags: [],
//         costForTwo: 40000,
//         costForTwoString: "₹400 FOR TWO",
//         deliveryTime: 45,
//         minDeliveryTime: 45,
//         maxDeliveryTime: 45,
//         slaString: "45 MINS",
//         lastMileTravel: 4,
//         slugs: {
//           restaurent: "sharief-bhai-ashwath-nagar-cross-road-marathahalli",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "# Site No- 39/2, Ground Floor, NS Complex, Ashwath Nagar Cross Road, Kundalahalli, Bangalore : 560037",
//         locality: "Ashwath Nagar",
//         parentId: 5734,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         ribbon: [
//           {
//             type: "PROMOTED",
//           },
//         ],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 3800,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 3800,
//           message: "",
//           title: "Delivery Charge",
//           amount: "3800",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "cid=7117957~p=13~eid=00000188-cd90-b604-1228-3c3d00af0d34",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "4 kms",
//         hasSurge: false,
//         aggregatedDiscountInfoV3: {
//           header: "40% OFF",
//           subHeader: "UPTO ₹80",
//           discountTag: "",
//           headerTypeV2: 0,
//         },
//         sla: {
//           restaurentId: "453491",
//           deliveryTime: 45,
//           minDeliveryTime: 45,
//           maxDeliveryTime: 45,
//           lastMileTravel: 4,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: true,
//         avgRating: "4.1",
//         totalRatings: 5000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "636313",
//         name: "The Rameshwaram Cafe",
//         uuid: "ee7e2a22-42c6-4f59-b0a1-d1df6faf403d",
//         city: "1",
//         area: "Brookefield",
//         totalRatingsString: "10000+ ratings",
//         cloudinaryImageId: "0adee855c65fa947a256764a87a55658",
//         cuisines: ["South Indian"],
//         tags: [],
//         costForTwo: 25000,
//         costForTwoString: "₹250 FOR TWO",
//         deliveryTime: 29,
//         minDeliveryTime: 29,
//         maxDeliveryTime: 29,
//         slaString: "29 MINS",
//         lastMileTravel: 1.7999999523162842,
//         slugs: {
//           restaurent: "the-rameshwaram-café-whitefield-whitefield",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "AIKYAM - THE RAMESHWARAM CAFE PLOT NO. 01, ITPL MAIN ROAD, GREEN AVENUE - BENGALURU, INDIA, B.B.M.P East, Karnataka-560037",
//         locality: "ITPL Main road",
//         parentId: 384316,
//         unserviceable: false,
//         veg: true,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 2800,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 2800,
//           message: "",
//           title: "Delivery Charge",
//           amount: "2800",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "1.7 kms",
//         hasSurge: false,
//         sla: {
//           restaurentId: "636313",
//           deliveryTime: 29,
//           minDeliveryTime: 29,
//           maxDeliveryTime: 29,
//           lastMileTravel: 1.7999999523162842,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.6",
//         totalRatings: 10000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "687845",
//         name: "Sri Udupi Food Hub",
//         uuid: "a4d303ff-66f8-42ac-963d-fb24a009b0be",
//         city: "1",
//         area: "Whitefield",
//         totalRatingsString: "100+ ratings",
//         cloudinaryImageId: "4a86036d4eb790361071316c658b8e88",
//         cuisines: [
//           "South Indian",
//           "North Indian",
//           "Indian",
//           "Chinese",
//           "Chaat",
//           "Ice Cream",
//           "Desserts",
//         ],
//         tags: [],
//         costForTwo: 19900,
//         costForTwoString: "₹199 FOR TWO",
//         deliveryTime: 33,
//         minDeliveryTime: 33,
//         maxDeliveryTime: 33,
//         slaString: "33 MINS",
//         lastMileTravel: 5.5,
//         slugs: {
//           restaurent: "sri-udupi-food-hub-whitefield-whitefield-2",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "13/1b, Hope farm, Pattandur Agrahara Village, KR PURAM Hobli, Bangalore, KR Puram, BBMP East, Karnataka-560066",
//         locality: "KR Puram",
//         parentId: 7550,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         ribbon: [
//           {
//             type: "PROMOTED",
//           },
//         ],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 5300,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 5300,
//           message: "",
//           title: "Delivery Charge",
//           amount: "5300",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "cid=7150248~p=19~eid=00000188-cd90-b604-1228-3c3f00af134e",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "5.5 kms",
//         hasSurge: false,
//         aggregatedDiscountInfoV3: {
//           header: "40% OFF",
//           subHeader: "UPTO ₹80",
//           discountTag: "",
//           headerTypeV2: 0,
//         },
//         sla: {
//           restaurentId: "687845",
//           deliveryTime: 33,
//           minDeliveryTime: 33,
//           maxDeliveryTime: 33,
//           lastMileTravel: 5.5,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: true,
//         avgRating: "3.7",
//         totalRatings: 100,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurent",
//       data: {
//         type: "F",
//         id: "237231",
//         name: "Burger King",
//         uuid: "69135cda-442c-4f08-9932-c26542624114",
//         city: "1",
//         area: "Hoodi",
//         totalRatingsString: "1000+ ratings",
//         cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
//         cuisines: ["Burgers", "American"],
//         tags: [],
//         costForTwo: 35000,
//         costForTwoString: "₹350 FOR TWO",
//         deliveryTime: 48,
//         minDeliveryTime: 48,
//         maxDeliveryTime: 48,
//         slaString: "48 MINS",
//         lastMileTravel: 2.799999952316284,
//         slugs: {
//           restaurent: "burger-king-forum-shantinikethan-mall-whitefield",
//           city: "bangalore",
//         },
//         cityState: "1",
//         address:
//           "Food Court, 3rd Floor, Forum Shantinikethan Mall 3rd floor Whitefield Main Road, Hoodi Bangalore 560048",
//         locality: "Forum Shantinikethan Mall",
//         parentId: 166,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 2800,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 2800,
//           message: "",
//           title: "Delivery Charge",
//           amount: "2800",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "2.7 kms",
//         hasSurge: false,
//         aggregatedDiscountInfoV3: {
//           header: "60% OFF",
//           subHeader: "UPTO ₹120",
//           discountTag: "",
//           headerTypeV2: 0,
//         },
//         sla: {
//           restaurentId: "237231",
//           deliveryTime: 48,
//           minDeliveryTime: 48,
//           maxDeliveryTime: 48,
//           lastMileTravel: 2.799999952316284,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.8",
//         totalRatings: 1000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//   ];
  
//   export default restaurentList;